### ISSUE TITLE
test execution dependant upon class name order and fails with TestNGException:  No free nodes found

### ISSUE THREAD

**Issue by t-weil** [testng-team/testng#1156]
Using dependsOnMethods to make a test class dependent of a method of a different class fails when the class names have the "wrong" order.

Example:

``` java
public class ATest {
    @Test(dependsOnMethods="test.BTest.test")
    public void test() {
    }
}
public class BTest {
    @Test
    public void test() {
    }
}
```

results in 

```
org.testng.TestNGException: 
No free nodes found in:[DynamicGraph 
  Ready:[ATest.test()[pri:0, instance:test.ATest@126e4ecd], BTest.test()[pri:0, instance:test.BTest@72b1f125]]
  Running:[]
  Finished:[]
  Edges:
     BTest.test()[pri:0, instance:test.BTest@72b1f125]
        ATest.test()[pri:0, instance:test.ATest@126e4ecd]
     ATest.test()[pri:0, instance:test.ATest@126e4ecd]
        BTest.test()[pri:0, instance:test.BTest@72b1f125]
]
```

If the dependency would be reversed, (B depends on A) the test is running fine.

TestNG version: 6.9.10

**Comment by juherr** [comment]
@t-weil As a workaround, you can configure the `preserve-order` option to `false`.

@cbeust I think something should be improved in dependency graph where a weight is clearly missing in case of conflict. Here: `dependsOnMethods` > `preserve-order`.
But what about the weight order of `dependsOnGroups` or `priority`?
As I understand https://github.com/cbeust/testng/issues/72 : `priority` > `dependsOnMethods` > `preserve-order` but it is easy to write an example with cycle using different rules. 
Have you already written something like that in one of your projects using graphs?

**Comment by cbeust** [comment]
No, I haven't written anything like that. TestNG's dependency weights have
become pretty complex and their interaction can be tricky.

Usually, you will typically not mix them, though.

-- 
Cédric

**Comment by juherr** [comment]
For sure, but `preserve-order` is activated by default (which is the expected case for most of the users IMO) and it is not logic to have to deactivate it in some cases.
For the moment, the current weight of orderers depends on the internal workflow and it results in some strange behaviors: `preserve-order` > `dependsOnMethods`.

That's why providing a weight (even not the good one) on orderers will assure us to have always the same consistent behavior in case of refactoring on the workflow and help us to explain it to users.

Just tell me what is your favorite order of the day (because we will be able to change it later) between `priority`, `dependsOnMethods`, `dependsOnGroups` and `preserve-order`

**Comment by cbeust** [comment]
`(dependsOnMethods/dependsOnGroups) > priority > preserve-order`
