### ISSUE TITLE
Ability to mark a method as a testng step (Possible enhancement)

### ISSUE THREAD

**Issue by motivatedmind** [testng-team/testng#2996]
### TestNG Version
> 7.8.0

### Expected behavior (Possible enhancement)

I have an Order class as below 

```
public class Order {

    // new hypothetical annotation from testng to mark a java method as a Step
    @Step("Prepare payload for the new customer order")
    public void prepareDataForOrder() {
        //TODO
    }

    @Step("Submit payload to create order api")
    public void submitOrder() {
        //TODO
    }

    @Step("Verify order parameters in db")
    public void verifyOrderInBackend() {
        //TODO
    }
}
```

I have a test method as below that calls Order module class

```
 @Test(description = "Create new order")
  public void createNewOrder(){
    Order order = new Order();
    order.prepareDataForOrder();
    order.submitOrder();
    order.verifyOrderInBackend();
  }
```
As in above Order class if testng can provide an annotation let's say @Step then using listeners or something like @BeforeStep or @AfterStep, we will be able to generate detailed manual test scripts in excel including the steps in the test case.

### Actual behavior
Currently as a test automation lead I often need to dry run my tests using -Dtestng.mode.dryrun=true to get holistic test coverage without executing tests. But I can only retrieve the test method name or test method description and not the steps as currently there is nothing can mark a method as a test Step

Alternately if there is a already a way to achieve this pls provide details.

** Note I don't want to move to BDD, as the cucumber lacks lot of powerful features in testng. **

**Comment by krmahadevan** [comment]
@motivatedmind - I think you should look at AOP programming and leveraging the ability to use a library such as [AspectJ](https://www.baeldung.com/aspectj) to define pointcuts and use them to build whatever capabilities you would like to have.

You can look at how Allure is doing this currently for references : https://github.com/allure-framework/allure-java

I say this because TestNG recognizes a method (method which is annotated using TestNG recognized annotations) as the smallest unit of execution. 

For your use case, I think AOP would be the solution that you need to pursue. 

On a side note, please do take a look at allure reporting. I believe it provides you a solution out of the box without you having to build anything from your side.

Refer: 

1. https://allurereport.org/docs/frameworks/java/junit5/
2. https://allurereport.org/modules/

Closing this issue, since its outside the scope of TestNG and is something that can be currently done.
