### ISSUE TITLE
Spring Framework and ITestListener dependency injections

### ISSUE THREAD

**Issue by vessosa** [testng-team/testng#2998]
### TestNG Version
7.8.0

Is there a way to inject my spring framework application context inside my implementation of ITestListener?
TestNG will always instantiate my listener (before the app context is loaded), so it's not managed by Spring.
I tried to invoke the tests manually and set the listener, but TestNG is responsible for instantiating it, so it invokes the nonargument constructor.
In other words, I would like to use some beans autowired inside the listener class, but the only option I have is creating a new application context; I want it to reuse the same from my test classes (that extends AbstractTestNGSpringContextTests).

**Comment by juherr** [comment]
That's a question for Spring.

**Comment by krmahadevan** [comment]
Since the object lifecycle management between spring and testng are completely different, in simple terms you would need to build a bean bag querying mechanism that looks like below

<details>

<summary>BeanBag</summary>

```java
import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;

@Component
public class BeanBag implements ApplicationContextAware {
    private static BeanBag instance;
    private ApplicationContext context;

    public BeanBag() {
        instance = this;
    }

    public static <T> T getObject(Class<T> type) {
        return instance.context.getBean(type);
    }

    @Override
    public void setApplicationContext(ApplicationContext context) throws BeansException {
        this.context = context;
    }
}

```

</details>

<details>
<summary>This is how the sample config will look like</summary>

```java
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class SampleConfig {

    @Bean
    public Employee employee() {
        return new Employee("Master Shifu", 40);
    }
    public record Employee(String name, int age) {

        @Override
        public String toString() {
            return String.format("Employee {%s, %d}", name, age);
        }
    }
}
```

</details>

<details>
<summary>This is how the test listener looks like</summary>

```java
import com.rationaleemotions.demo.config.SampleConfig;
import org.testng.ITestListener;
import org.testng.ITestResult;

public class ExampleListener implements ITestListener {

    @Override
    public void onTestStart(ITestResult result) {
        System.err.println(">>>>>>" + BeanBag.getObject(SampleConfig.Employee.class));
    }
}
```

</details>


<details>

<summary>Sample test case</summary>

```java
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@SpringBootTest
@Listeners(ExampleListener.class)
public class DemoApplicationTests extends AbstractTestNGSpringContextTests {

    @Test
    public void contextLoads() {
        System.err.println("Hello world");
    }
}
```

</details>

execution output:

```shell
2023-10-24T12:17:38.267+05:30  INFO 19385 --- [           main] c.r.demo.DemoApplicationTests            : Starting DemoApplicationTests using Java 17.0.8 with PID 19385 (/Users/kmahadevan/githome/playground/spring_test_demo/target/test-classes started by kmahadevan in /Users/kmahadevan/githome/playground/spring_test_demo)
2023-10-24T12:17:38.269+05:30  INFO 19385 --- [           main] c.r.demo.DemoApplicationTests            : No active profile set, falling back to 1 default profile: "default"
2023-10-24T12:17:39.287+05:30  INFO 19385 --- [           main] c.r.demo.DemoApplicationTests            : Started DemoApplicationTests in 1.316 seconds (process running for 2.437)
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
>>>>>>Employee {Master Shifu, 40}
Hello world

===============================================
Default Suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0
```

**Comment by vessosa** [comment]
@krmahadevan Thank you for your answer.

That works as you override onTestStart. I was trying to override onStart.
`    @Override
    public void onStart(ITestContext context) {
        System.err.println(">>>>>>" + BeanBag.getObject(SampleConfig.Employee.class));
    }`

Will result in:
`java.lang.NullPointerException: Cannot read field "context" because "com.example.springboottestngtestsdemo.BeanBag.instance" is null

Test ignored.
	at com.example.springboottestngtestsdemo.BeanBag.getObject(BeanBag.java:18)
	at com.example.springboottestngtestsdemo.ExampleListener.onStart(ExampleListener.java:12)`


@juherr Thanks for your feedback; my idea was to request to check if this is something that could be changed. The onStart method is invoked before the Spring App Context loads.

**Comment by krmahadevan** [comment]
@vessosa 

* `org.springframework.test.context.testng.AbstractTestNGSpringContextTests` is NOT owned by TestNG but its owned by the spring eco-system. So we have no control on when what gets called.
* > my idea was to request to check if this is something that could be changed. The onStart method is invoked before the Spring App Context loads.

Yes, you are correct, but `onStart()` is being called by TestNG before starting to run any `@Test` methods within a `<test>` tag, but `AbstractTestNGSpringContextTests` is initialising the spring application context only when it runs the `@BeforeClass` that is part of it. So `onStart()` is ALWAYS bound to happen before calling `@BeforeClass`. This cannot be altered in TestNG because the semantics would change. Perhaps you can either request for an alternate from the Spring community (or) you could create your own base class similar to `AbstractTestNGSpringContextTests` and work with it.

I am not sure what additionally can be done here. But the crux of the change is all isolated to `AbstractTestNGSpringContextTests` which is NOT within the scope of TestNG.

**Comment by vessosa** [comment]
@krmahadevan Thank you for your response and for clarifying the situation. I truly appreciate your insights and understanding!
