### ISSUE TITLE
@BeforeSuite and @AfterSuite notation

### ISSUE THREAD

**Issue by pierrehub2b** [testng-team/testng#3032]
### TestNG Version
7.9.0

### Expected behavior
no issue

### Actual behavior
execution of test failed with following logs: 
_**Native Injection is NOT supported for @BeforeSuite annotated beforeSuite.**_

### Test case sample

create a test case with a 'beforeSuite' method like this: 

```
	@BeforeSuite(alwaysRun = true)
	public void beforeSuite(ITestContext ctx) {
	}
```

this annotation was working in previous version of TestNG (from 6.13.1 to 7.8.0)

**Comment by krmahadevan** [comment]
For a `@BeforeSuite` and `@AfterSuite` `ITestContext` ( this represents a `<test>` tag) is NOT relevant because if a `<suite>` tag contains 2 or more `<test>` tags, then which `ITestContext` object to inject becomes a question and also at a suite level, test level is not relevant because `<test>` tag is a child of the `<suite>` tag.

This was fixed as part of https://github.com/testng-team/testng/issues/2925

You can use `Reporter.getCurrentTestResult()` within your `@BeforeSuite` method and then work with it.

**Comment by pierrehub2b** [comment]
the problem is that this methods are not called anymore with 7.9.0.

**Comment by krmahadevan** [comment]
@pierrehub2b - I didnt quite understand what you meant. Can you please clarify?

**Comment by krmahadevan** [comment]
You can also refer to a similar issue that was recently closed with the same resolution https://github.com/testng-team/testng/issues/3029

This issue also has a sample that can be used.

**Comment by pierrehub2b** [comment]
when I launch a test execution with a java command line in debug mode, I have set a breakpoint with Eclipse int the method 'beforeSuite', the breakpoint is no more reached with the 7.9.0 version.
with 7.8.0 version I can see the execution reached the breakpoint

**Comment by krmahadevan** [comment]
Have you tried setting up breakpoints to the sample that I had shared in the comments of #3029 ? Also maybe you need to also update the TestNG eclipse plugin ( I think it also went through with an update recently. Please correct me if I am wrong @missedone )

**Comment by pierrehub2b** [comment]
ok, it works now, I thaught we need to remove '(alwaysRun = true)' notation too with this last version.
Thanks for the example, it helps me to understand this evolution.

You can close this issue

Thank you for your time
