### ISSUE TITLE
Class with annotation @Test(singleThreaded=true) has tests execed in multiple threads.

### ISSUE THREAD

**Issue by gavares** [testng-team/testng#54]
I have a class declared like:

@Test(singleThreaded=true)
public class UT_Database extends ProjectDataServiceTestCase {

}

After running the tests in this class, I can see on the TestNG HTML report that the two test methods in the class ran on different threads. 

11/06/17 15:38:07   1079                        testOfflineColumns  pool-2-thread-1@770476297  
11/06/17 15:38:13   7084                        testNonTrivialDatabase  pool-2-thread-2@506532880   

This seems to be in violation of the language describing the singleThreaded attribute and is causing my tests to fail. 

Am I missing something?  I'm using ant tasks to execute the tests. The resulting generated testng.xml follows: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="2" verbose="5" name="Ant suite" parallel="classes">
  <test name="Ant test" preserve-order="false">
    <classes>
      <class name="com.test.db.UT_Database"/>
    </classes>
  </test>
</suite>
```

**Comment by adrian-herscu-ge** [comment]
Same behavior for me on 6.14.3 and on 7.0.0-beta3 :(

**Comment by krmahadevan** [comment]
@adrian-herscu-ge

Do you think you could help share a simple standalone project/test code
that can be used to reproduce the issue ?

**Comment by adrian-herscu-ge** [comment]
A bit busy...

This is what I can share for now:

```
<suite name="system-testing" verbose="1" parallel="tests">
  <test name="SomeTest">
    <classes>
      <class  name="SomeTest"/>
    </classes>
  </test>

  <test name="AnotherTest">
    <classes>
      <class name="AnotherTest"/>
    </classes>
  </test>
...
```
```
@Test(singleThreaded = true)
public class SomeTest {
...
```

These classes use a Selenium driver to run GUI tests. The driver is instantiated in one method and all other methods are defined with `dependsOnMethod` in order to reuse that driver, otherwise things will run really slow (initializing the application and logging in again). I discovered, that although the required order is preserved according to `dependsOnMethod`, the different methods are executed on different threads, and since I am storing the driver in a `ThreadLocal`, that driver is no longer found :( So added `singleThreaded = true` hoping to cure the problem....

**Comment by krmahadevan** [comment]
@adrian-herscu-ge - When you do find the time, please do help share a simple standalone test (preferably one that doesn't use any 3rd party libraries such as selenium etc., ) and we can take a look at it. What you have shared is not sufficient to dig in and investigate.

**Comment by Animedium** [comment]
Here is a pice of code that I was using for testing different TestNG configurations and behavior. I run it from Gradle but should work however you would run it. With having it set to run with 2 threads it will run second thread from the second method setup even when having singleThreaded enabled.

Hope this will help!

`package com.veracode.tests.ui.onewasTest;
import org.testng.Reporter;
import org.testng.annotations.*;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.List;
@Test(groups = "tests2", singleThreaded = true)
public class TestNGTestTWO {
    ThreadLocal<Long> ID = ThreadLocal.withInitial(() -> Thread.currentThread().getId());
    @BeforeClass(alwaysRun = true)
    private void classSetup(){
        long id = Thread.currentThread().getId();
        System.out.println("Before class - Thread id is: " + id);
        System.out.println("Before class - ID is: " + ID.get());
    }
    @BeforeMethod(alwaysRun = true)
    private void setup1(Method test){
        System.out.printf("Setup 1 for test %s%n", test.getName());
        long id = Thread.currentThread().getId();
        System.out.println("Before method - Thread id is: " + id);
        System.out.println("Before method - ID is: " + ID.get());
    }
    @Test
    public void test1(){
        System.out.println("Test 1");
        long id = Thread.currentThread().getId();
        System.out.println("test - Thread id is: " + id);
        System.out.println("test - Thread - ID is: " + ID.get());
        String method = Reporter.getCurrentTestResult().getMethod().getMethodName();
        System.err.println("Running " + getClass().getName() + "." + method + "() on Thread [" + Thread.currentThread()
                .getId() + "]");
    }
    @Test(dependsOnMethods = "test1")
    public void test2(){
        System.out.println("Test 2");
        long id = Thread.currentThread().getId();
        System.out.println("test - Thread id is: " + id);
        System.out.println("test - Thread - ID is: " + ID.get());
        String method = Reporter.getCurrentTestResult().getMethod().getMethodName();
        System.err.println("Running " + getClass().getName() + "." + method + "() on Thread [" + Thread.currentThread()
                .getId() + "]");
    }
    @AfterMethod(alwaysRun = true)
    private void teardown1(){
        System.out.println("Teardown 1");
        long id = Thread.currentThread().getId();
        System.out.println("after method - Thread id is: " + id);
        System.out.println("after method - ID is: " + ID.get());
    }
    @AfterMethod(alwaysRun = true, dependsOnMethods = {"teardown1"})
    private void teardown2(Method test){
        List<String> methods = Arrays.asList("test1");
        if(!methods.contains(test.getName())) return;
        System.out.println("Teardown 2");
        long id = Thread.currentThread().getId();
        System.out.println("after class - Thread id is: " + id);
        System.out.println("after class - ID is: " + ID.get());
    }
    @AfterClass(alwaysRun = true)
    private void classTeardown(){
        long id = Thread.currentThread().getId();
        System.out.println("After class - Thread id is: " + id);
        System.out.println("After class - ID is: " + ID.get());
    }
}`

**Comment by agentbars007** [comment]
Still actual for me
Cod upper shows how it happens.
Looks like 'dependsOnMethods' turns off the 'Singlethreaded'

**Comment by krmahadevan** [comment]
@agentbars007 - I think you perhaps have hit a design edge case maybe?

* TestNG chooses the execution strategy based on the parallel attribute. 
* You have indicated that you would like to have parallelism enabled by specifying `setParallel("methods")`. 
* So TestNG chooses an executor that is capable of running tests in parallel. 
* That executor filters out tests that can run independently and runs them. 
* Once all the independent tests have run to completion, it picks up all the dependent tests and then continues to run them.
* Since this is an executor service, there's no guarantee that can be made that you will be given thread affinity, which explains why you are seeing different threads.

**The fix:**

* Please get rid of `setParallel("methods")` for these sequential tests. Maybe create a suite xml for them separately and then run them.  (or)
* Use the JVM argument to enable thread affinity (can be enabled by passing `-Dtestng.thread.affinity=true` as a JVM argument when running your gradle tests) and then try running the tests. This would ensure that both the dependent and independent methods are run in the same thread. 

**Please note that this is an experimental feature and may not address all your edge cases.** 

Also please don't forget to upgrade to the latest release (`7.5.1` if u are on JDK8, and `7.8.0` if u are on JDK11)

Below are the only two types of methods wherein thread affinity is guaranteed to work.

* Your tests have a soft ordering (i.e., you use priorities)
* Your tests use a `dependsOnMethods` but the upstream dependency is limited to the current test depending on utmost one method. If you have more than 1 methods upon which you depend on, TestNG will NOT honour thread affinity
