### ISSUE TITLE
Excessive memory due to retaining ITestResult#getParameters()

### ISSUE THREAD

**Issue by ben-manes** [testng-team/testng#584]
[This test suite](https://github.com/ben-manes/caffeine) makes heavy use of parameterized tests to validate all of the configurations of a builder for each test method. This generates thousands of tests, which is wonderful for asserting coverage of all the complex combinations that might occur. Unfortunately due to the large constructed objects, the memory usage was high. This constantly failed on TravisCI due to the process exceeding the memory quota. 

This was surprising because after a test executes, its parameters should be GC'able due to using streaming iterators for the data provider. When profiling, it was clear that TestNG is holding onto the parameters, most likely for reporting purposes.

The [solution](https://github.com/ben-manes/caffeine/blob/master/src/test/java/com/github/benmanes/caffeine/cache/testing/CacheValidationListener.java) was to implement an `IInvokedMethodListener` that cleared the parameters after execution. To satisfy the Eclipse plugin's report, the parameter index is set to its `toString()` value.

This sped up the build, profiling shows a steady low memory usage, and the CI is stable. I think a similar solution could be embedded into TestNG without breaking the user-visible life-cycle, so reporting the findings as an enhancement request.

**Comment by krmahadevan** [comment]
@ben-manes - I am not sure if it would be proper to implement such sort of a cleanup logic within TestNG because I have seen people resort to trying to print the parameters associated with an `ITestResult` (which is a representation of every method) within reports.

If TestNG ends up cleaning up these parameters of every `ITestResult` then they will not be available for the reports. 
If we choose to clean them up at reporting phase within TestNG, it perhaps is either too late (or) we will still be impacting some other reports that may run after TestNG's default reports.

IMO this sort of logic should exist within a test repository that is populating the parameters for a Test method and then based on the repo needs, it should eagerly clean up the parameters as needed.

@juherr  WDYT ?

**Comment by krmahadevan** [comment]
ping @juherr - Please let me know your thoughts on this.

**Comment by juherr** [comment]
I think we can do something: `ITestResult#getParameters()` exists and is stored for the reporters.
But if we have no reporter, there is no reason to keep everything in memory.

An option could be to have a dedicated part for reporters which is notified by `ITestResult`s and stores them only if there are reporters.

**Comment by krmahadevan** [comment]
@juherr - I did think about that. But in a real world use-case, people would be having some sort of reporting needs as well. So I can't think of a practical use-case when this would be needed.

Moreover, since the users would know what they are passing in as parameters etc., for their test methods, wouldn't they be the best set of people to decide whether the parameters should stay or be wiped off from the corresponding `ITestResult` object, rather than TestNG making that educated guess ?

**Comment by juherr** [comment]
People can't decide because it depends on the reporter they use.

IMO, there is a real architecture issue because we are storing in memory something which can be very big. It is not the general case but it exists.

I think the reporter logic (store information and notify reporters at the end) should just be a customer of specific listeners.
Maybe we can offer a way to users to configure the reporter logic :)

**Comment by ben-manes** [comment]
Closing as similar to #2096
