### ISSUE TITLE
Missing release files on jcenter.bintray.com

### ISSUE THREAD

**Issue by bsdkurt** [testng-team/testng#749]
The following page indicates there should be released binaries available:

http://testng.org/doc/download.html

However, the binaries are missing. See the following page:

http://jcenter.bintray.com/org/testng/testng/

Please upload the released binaries. Thank you.

-Kurt

**Comment by cbeust** [comment]
Mmmh... indeed, I thought they were already on JCenter but it looks like they are only available on `http://dl.bintray.com/cbeust/maven` (which is where `publish` put them, and apparently not JCenter):

https://bintray.com/cbeust/maven/testng/6.9.4/view#files

Any idea what I need to do to publish these files to JCenter?

**Comment by cbeust** [comment]
I thought I had already linked the repo to JCenter but apparently, this was not the case. I filed the request.

**Comment by juherr** [comment]
@cbeust Could it explain your issue with the deployment on maven central?

**Comment by cbeust** [comment]
@juherr No, there are unrelated. Maven Central is unhappy because the current build process doesn't create the `sha1`, `md5` and `asc` files. Somehow, I was able to create those for 6.9.4:

https://bintray.com/cbeust/maven/testng/6.9.4/view#files

and I was able to deploy this to Maven Central without anyproblems, but when I try to deploy 6.9.5, these files don't get created. Probably something silly that I broke in the build file but I can't figure it out so far.

**Comment by bsdkurt** [comment]
Thanks for fixing this. I see the released binaries are showing up on in http://jcenter.bintray.com/org/testng/testng/.

On a separate note, I see 6.9.5 is released. Although git is missing the release tag here:

https://github.com/cbeust/testng/releases

**Comment by cbeust** [comment]
Fixed!

-- 
Cédric

**Comment by krmahadevan** [comment]
Stale issue. Closing. Please comment if this is still a problem.
